version: '3.8'
services:
  spanner-emulator:
    image: gcr.io/cloud-spanner-emulator/emulator:1.3.0
    ports:
     - "127.0.0.1:9010:9010"
     - "127.0.0.1:9020:9020"
    environment:
     - SPANNER_EMULATOR_HOST=localhost:9010
  pubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:360.0.0
    command: ["gcloud", "beta", "emulators", "pubsub", "start", "--project=test-project", "--host-port=127.0.0.1:8085"]
    ports:
     - "127.0.0.1:8085:8085"
    environment:
     - SPANNER_EMULATOR_HOST=localhost:9010
     - PUBSUB_EMULATOR_HOST=localhost:8085
     - PUBSUB_PROJECT_ID=test-project
